package broker;

import experiments.measurement.MeasurementProducerBroker;

public interface AsynchronousMeasurementProducerCachingBroker extends AsynchronousCachingBroker, MeasurementProducerBroker {}