package marketplace.simulations;

import java.util.Properties;
import simulator.experimentation.SimulationScenario;
import simulator.simulations.performance.metrics.PerformanceMetricsData;
import simulator.simulations.performance.metrics.RegionPerformanceMetricsData;
import marketplace.topology.MarketplaceBrokerFactory;

/**
 * Encapsulates the execution and metric extraction for the Privacy-Preserving 
 * FaaS Marketplace experiments across the Edge-Cloud Continuum.
 */
public class MarketplaceScenario implements SimulationScenario {

    @Override
    public String getKnobKey() {
        // While MarketplaceBatchOrchestrator drives its own multi-variable sweep, 
        // we satisfy the interface here with our primary structural knob.
        return "broker.smartThreshold";
    }

    @Override
    public String[] getKnobValues() {
        return new String[] { "0.10", "0.25", "0.50", "0.75", "1.00" };
    }

    @Override
    public String getCsvHeader() {
        // Updated FaaS Marketplace metrics:
        // 1. table_size_avg: Memory overhead at Edge/Fog brokers.
        // 2. pub_events: Forwarding overhead for ServiceRequests.
        // 3. total_he_comparisons: Total cryptographic overhead of Paillier blind matching.
        // 4. sub_updates_sent: Churn generated by dynamic ServiceOffers.
        // 5. filtered_updates: Subscriptions and Publications proactively stopped by spatial/QoS shielding.
        // 6. dead_ends: Requests routed down a path that could not fulfill them.
        // 7. optimal_matches: The theoretical maximum satisfiable requests (from Ground Truth).
        // 8. accuracy: Ratio of actual decentralized deliveries vs theoretical optimal matches.
        return "table_size_avg,pub_events,total_he_comparisons,sub_updates_sent,filtered_updates,dead_ends,optimal_matches,accuracy";
    }

    @Override
    public String getCsvRow(PerformanceMetricsData data, Properties props) {
        if (!(data instanceof simulator.simulations.performance.metrics.RegionPerformanceMetricsData regionData)) {
            return "";
        }

        double avgTableSize = regionData.inputTableStats.getAverage();
        long pubEvents = regionData.totalPublicationProcessingEvents;
        
        // Now capturing absolute sum of matchin operations
        long totalHeComparisons = regionData.totalMatchingComputations; 
        
        long subOverhead = regionData.totalPropagatedExpanded + regionData.totalPropagatedAdded;
        
        // Filtered events (Proactive shielding of requests + State suppressed by Hypercube covering)
        long filteredUpdates = regionData.totalProactiveShieldedEvents + regionData.totalInputCovered;
        
        // Dead ends (False positives where intent could not be resolved downstream)
        long deadEnds = regionData.totalDownwardDeadEndEvents;
        
        long optimalMatches = regionData.groundTruthMatches; 
        long deliveries = regionData.totalDeliveriesReceived;
        
        // Decentralized routing accuracy
        double accuracy = (optimalMatches > 0) ? (double) deliveries / optimalMatches : 0.0;

        return String.format("%.2f,%d,%d,%d,%d,%d,%d,%.4f",
                avgTableSize, 
                pubEvents, 
                totalHeComparisons, 
                subOverhead, 
                filteredUpdates, 
                deadEnds, 
                optimalMatches,
                accuracy
        );
    }

    @Override
    public void configure(Properties props) {
        // Enforce FaaS Marketplace-specific routing behaviors prior to Simulator initialization.
        // We ensure strict propagation policies to test the bounds of the QoS Hypercube.
        props.setProperty("broker.brake.strategy", "simulator.regions.policy.NoOpBrakeStrategy");
    }

    @Override
    public PerformanceMetricsData runSimulation() {
        // 1. Instantiate the Systematic Multi-Objective Workload Simulator
        var sim = new SystematicMarketplaceContinuumSimulation();
        
        // 2. Prepare the Edge-Cloud Continuum Topology
        MarketplaceTopologyConfiguration config = new MarketplaceTopologyConfiguration();
        MarketplaceTopologyLoader factory = new MarketplaceTopologyLoader(config, new MarketplaceBrokerFactory());
        
        // 3. Execute the Run
        sim.run(factory, config);
        
        // 4. Return the aggregated telemetry
        return sim.getLastRunMetrics();
    }
}