package simulator.topology;

import java.util.Random;

import simulator.TreeNode;

/**
 * Abstract base class for topology factories, defining the steps for generation.
 *
 * @param <C> The specific type of TopologyConfiguration required by the subclass.
 * @param <R> The specific type of the root TreeNode generated by the subclass.
 */
public abstract class AbstractTopologyFactory<C extends TopologyConfiguration, R extends TreeNode> implements TopologyFactory {

    protected C config; // Store the specific configuration type
    protected final Random random = new Random();
    protected int brokerIdCounter = 0;
    protected int leafBrokerIdCounter = 0;
    protected int subscriberIdCounter = 0;
    protected int publisherIdCounter = 0;
    protected R rootNode = null;

    @Override
    public final TreeNode generateTopology(TopologyConfiguration genericConfig) {
        // 1. Initialisation (includes validation and type casting)
        initialise(genericConfig); // This method handles casting and stores the config

        // 2. Build Core Structure (e.g., Brokers)
        this.rootNode = buildCoreTopology();
        if (this.rootNode == null) {
            throw new IllegalStateException("Core topology generation failed to produce a root node.");
        }

        // 3. Attach Subscribers to the core structure
        attachSubscribers(this.rootNode);

        // 4. Attach Publishers (if applicable for the simulation model)
        attachPublishers(this.rootNode);

        System.out.println("Topology generation complete. Root: " + this.rootNode.getName());
        return this.rootNode; // Return the specifically typed root
    }

    /**
     * Initialises the factory with the specific configuration, performs validation,
     * resets state (like counters), and performs any type-specific setup
     * (e.g., generating regions).
     * This method MUST handle casting the generic config to the specific type C
     * required by the subclass and store it in the 'config' field.
     *
     * @param genericConfig The generic configuration object passed to generateTopology.
     * @throws IllegalArgumentException if the configuration is not of the expected type or is invalid.
     */
    protected abstract void initialise(TopologyConfiguration genericConfig);

    /**
     * Builds the main hierarchical structure of the topology (e.g., brokers).
     * Assumes initialize() has been called successfully.
     *
     * @return The root node of the core topology (specifically typed as R).
     */
    protected abstract R buildCoreTopology();

    /**
     * Creates and attaches subscriber nodes to the appropriate leaf nodes
     * of the topology rooted at 'root'.
     * Assumes initialize() and buildCoreTopology() have been called successfully.
     *
     * @param root The root node of the topology (specifically typed as R).
     */
    protected abstract void attachSubscribers(R root);

    /**
     * Creates and attaches publisher nodes to the appropriate leaf nodes 
     *  of the topology rooted at 'root'.
     * Assumes initialize() and buildCoreTopology() have been called successfully.
     *
     * @param root The root node of the topology (specifically typed as R).
     */
    protected abstract void attachPublishers(R root);

    // Helper methods for generating unique names/IDs can be added here if desired
    protected String generateBrokerName() {
        return "Broker-" + brokerIdCounter++;
    }

    protected String generateLeafBrokerName() {
        return "Leaf-" + leafBrokerIdCounter++;
    }

    protected String generateSubscriberName() {
        return "Sub-" + subscriberIdCounter++;
    }

     protected String generatePublisherName() {
        return "Pub-" + publisherIdCounter++;
    }
}
