# --- Random Topology Defaults ---
topology.random.depth=4
topology.random.branching=4
topology.random.regions=100
topology.random.width=100.0
topology.random.height=100.0


# --- Grid Topology Defaults ---
topology.grid.dimension=10
opology.grid.overlapFactor=0.0


# --- GeoNames Topology Defaults ---
# Resources (DB) path
paths.resourcesDir=resources/world/
# Options: POLITICAL, RTREE
topology.strategy=POLITICAL

# Only used if strategy=RTREE
topology.rtreeBranchingFactor=20

# Toggles whether the full or the subset testing topology will be used
paths.useFullTopology=true


# --- Broker Behavior (Runtime) ---
# Options: SIMPLE (Always Aggregate), SMART (Threshold)
#broker.strategy=SMART
broker.strategy=SIMPLE
# Only used if strategy=SMART (0.0 to 1.0)
broker.smartThreshold=0.5

# --- Workload (Simulation) ---
workload.replicas=20
workload.subscribersPerReplica=2500
workload.subscriptionRegionSize=1.0
workload.remoteInterestProb=0.0

# --- Output Paths for Logs and Metrics ---
paths.outputDir=output/
paths.enableVerboseLogs=false