package simulator.topology.geonames.builder;

public interface TopologyBuilderStrategy {
    /**
     * Builds the broker hierarchy starting from the raw GeoNames file.
     */
    GeoNamesBuilderNode build(GeoNamesDataLoader loader, String geonamesFilePath);

    /**
     * Returns the desired filename for the JSON output generated by this strategy.
     * Example: "geonames_topology_political.json"
     */
    String getOutputFileName();
}