package simulator.tests.scenarios.proximity.e2e;

import simulator.core.Location;
import simulator.entities.PublisherWithLocation;
import simulator.entities.SimulationBroker;
import simulator.entities.SubscriberWithLocation;
import simulator.events.PublicationWithLocation;
import simulator.events.SubscriptionWithLocation;
import simulator.tests.framework.FunctionalTestUtils;
import simulator.tests.framework.TestScenario;
import simulator.tests.framework.TopologyFixture;

/**
 * End-to-End Check for Proximity Routing on a Grid Topology.
 * Verifies routing finds the path across the mesh and filters correctly
 * using floating point coordinates.
 */
public class ProximityGridTopologyE2ETest extends TestScenario {

    @Override
    public String getTestName() { 
        return "Proximity E2E: Grid Topology (Floating Point)"; 
    }

    @Override
    public boolean run(TopologyFixture fixture) {
        // 1. Locate Brokers (Leaf nodes of the grid)
        // Access specific leaves generated by the GridTopologyGenerator
        SimulationBroker leaf00 = fixture.findNode("leaf-0-0", SimulationBroker.class);
        SimulationBroker leaf22 = fixture.findNode("leaf-2-2", SimulationBroker.class); // Opposite corner
        SimulationBroker leaf01 = fixture.findNode("leaf-0-1", SimulationBroker.class); // Neighbor

        if (leaf00 == null || leaf22 == null || leaf01 == null) {
            logger.severe("Topology Error: Grid leaves not found.");
            return false;
        }

        // 2. Create Actors with Floating Point Coordinates
        // We create NEW entities because existing ones in fixture might not be where we want them.
        
        // Subscriber at Origin (0.1, 0.1)
        Location locSub = new Location(0.1, 0.1, 0);
        SubscriberWithLocation sub = new SubscriberWithLocation("GridSub", locSub);
        leaf00.addChild(sub);
        
        // Far Publisher (200.55, 200.55)
        Location locFar = new Location(200.55, 200.55, 0);
        PublisherWithLocation pubFar = new PublisherWithLocation("PubFar", locFar);
        leaf22.addChild(pubFar);
        
        // Close Publisher (0.1, 20.99)
        Location locClose = new Location(0.1, 20.99, 0);
        PublisherWithLocation pubClose = new PublisherWithLocation("PubClose", locClose);
        leaf01.addChild(pubClose);

        // 3. Subscribe
        sub.send(new SubscriptionWithLocation(locSub));

        // 4. Publish Sequence
        
        // A. Far Publisher -> ACCEPTED (First publication seen is always accepted)
        pubFar.send(new PublicationWithLocation(locFar));

        // B. Close Publisher -> ACCEPTED (Improvement: 20.89 < ~283.0)
        pubClose.send(new PublicationWithLocation(locClose));

        // C. Far Publisher Again -> REJECTED (Worse: ~283.0 > 20.89)
        pubFar.send(new PublicationWithLocation(locFar));

        // 5. Verify using Utils
        try {
            FunctionalTestUtils.assertReceived(sub, 2);
            logger.info("Success: Grid routing respected proximity filter.");
        } catch (AssertionError e) {
            logger.severe("Failure: " + e.getMessage());
            return false;
        }
        return true;
    }
}