import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as mtick
import numpy as np
import os

# ==========================================
# 1. CONFIGURATION & DATA LOADING
# ==========================================
PLOT_CI = True          # Set to False to turn off Confidence Interval shading
FIG_SIZE = (8, 4.0)     # Wider, shorter aspect ratio to save vertical space in LaTeX

FILE_EXP_1 = 'experiment1_budget_sweep.csv'
FILE_EXP_2 = 'experiment2_edge_sweep.csv'
FILE_EXP_3 = 'experiment3_continuum_sweep.csv'
FILE_EXP_4 = 'experiment4_30_edge.csv'

# Check for files and warn if missing
for f in [FILE_EXP_1, FILE_EXP_2, FILE_EXP_3, FILE_EXP_4]:
    if not os.path.exists(f):
        print(f"WARNING: '{f}' not found. Please ensure all CSVs are in the directory.")

# Set visual style for academic papers (IEEE/ICCCN standard)
sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)
colors = sns.color_palette("Set1")

# Semantic Colors
color_baseline = colors[0]     # Red-ish
color_marketplace = colors[1]  # Blue-ish
COLOR_OPTIMAL = '#2ca02c'      # Green for True Optimal
COLOR_SUBOPTIMAL = '#ff7f0e'   # Orange for Suboptimal
COLOR_SLA = '#d62728'          # Red for SLA Violations

# Labels
LABEL_BASELINE = 'Baseline FaaS Gateway'
LABEL_MARKETPLACE = 'Marketplace'

# --- CI Helper Function ---
def add_ci(ax, df_raw, strategy_val, x_col, y_col, color):
    """Calculates and plots a 95% Confidence Interval band based on raw run data."""
    if not PLOT_CI or df_raw is None or y_col not in df_raw.columns:
        return
    d = df_raw[df_raw['strategy'] == strategy_val] if strategy_val else df_raw
    grouped = d.groupby(x_col)[y_col]
    mean = grouped.mean()
    sem = grouped.sem().fillna(0)  # Handle 0 variance or single rep runs gracefully
    ci = 1.96 * sem                # Approx 95% Confidence Interval
    ax.fill_between(mean.index, mean - ci, mean + ci, color=color, alpha=0.15, linewidth=0)

# Load Data Part A
try:
    df1 = pd.read_csv(FILE_EXP_1)
    
    # Pre-calculate derived metrics on raw data for accurate CI variances
    df1['optimal_pct'] = (df1['true_optimal_deliveries'] / df1['deliveries']) * 100
    df1['suboptimal_pct'] = (df1['suboptimal_deliveries'] / df1['deliveries']) * 100
    df1['sla_pct'] = (df1['sla_violations'] / df1['deliveries']) * 100
    
    # Average data across multiple runs (rep_id) to prevent zig-zag lines
    df1_mean = df1.groupby(['strategy', 'sweep_value']).mean(numeric_only=True).reset_index()
    
    df1_base = df1_mean[df1_mean['strategy'] == 'BASELINE'].copy()
    df1_mkt = df1_mean[df1_mean['strategy'] == 'WEIGHTED_UTILITY'].copy()
except FileNotFoundError:
    df1_base, df1_mkt = None, None
    print("Skipping Experiment 1 plots: Data not found.")

# Load Data Part B
try:
    df2 = pd.read_csv(FILE_EXP_2)
    df3 = pd.read_csv(FILE_EXP_3)
    
    # Pre-calculate derived metrics on raw data for accurate CI variances
    df2['shielded_pct'] = (df2['shielded_requests'] / (df2['deliveries'] + df2['shielded_requests'])) * 100
    df3['shielded_pct'] = (df3['shielded_requests'] / (df3['deliveries'] + df3['shielded_requests'])) * 100
    
    df3['optimal_pct'] = (df3['true_optimal_deliveries'] / df3['deliveries']) * 100
    df3['suboptimal_pct'] = (df3['suboptimal_deliveries'] / df3['deliveries']) * 100
    df3['sla_pct'] = (df3['sla_violations'] / df3['deliveries']) * 100
    
    # Average data across runs for topological sweeps
    df2_mean = df2.groupby(['strategy', 'sweep_value']).mean(numeric_only=True).reset_index()
    df3_mean = df3.groupby(['strategy', 'sweep_value']).mean(numeric_only=True).reset_index()
    
    df2_mkt = df2_mean[df2_mean['strategy'] == 'WEIGHTED_UTILITY'].copy()
    
    # Extract both Baseline and Marketplace for Exp 3 comparisons
    df3_base = df3_mean[df3_mean['strategy'] == 'BASELINE'].copy()
    df3_mkt = df3_mean[df3_mean['strategy'] == 'WEIGHTED_UTILITY'].copy()
except FileNotFoundError:
    df2_mkt, df3_mkt, df3_base = None, None, None
    print("Skipping Experiment 2 & 3 plots: Data not found.")

# Load Data Part C (Experiment 4)
try:
    df4 = pd.read_csv(FILE_EXP_4)
    # The total number of requests generated by clients is the 'publishers' count (1,000,000).
    total_requests = df4['publishers']
    
    df4['optimal_pct'] = (df4['true_optimal_deliveries'] / total_requests) * 100
    df4['suboptimal_pct'] = (df4['suboptimal_deliveries'] / total_requests) * 100
    df4['dead_ends_pct'] = (df4['dead_ends'] / total_requests) * 100
    df4['shielded_pct'] = (df4['shielded_requests'] / total_requests) * 100
    
    # --- New Metrics for Fig 7b & 7c ---
    df4['undelivered_pct'] = ((df4['ground_truth_matches'] - df4['deliveries']) / total_requests) * 100
    df4['false_positive_pct'] = ((df4['dead_ends'] - (df4['ground_truth_matches'] - df4['deliveries'])) / total_requests) * 100
except FileNotFoundError:
    df4 = None
    print("Skipping Experiment 4 plots: Data not found.")


# Determine a shared Y-axis limit for the "Optimality Gap" (Unified System Degradation) across Exp 1 & Exp 3
max_deg = 0.0
if df1_base is not None and 'unified_system_degradation' in df1_base.columns:
    max_deg = max(max_deg, df1_base['unified_system_degradation'].max())
if df3_base is not None and 'unified_system_degradation' in df3_base.columns:
    max_deg = max(max_deg, df3_base['unified_system_degradation'].max())
shared_deg_ylim = (-0.02, max_deg * 1.15 if max_deg > 0 else 0.60)


# =====================================================================
# PART A: EXPERIMENT 1 - BUDGET CONSTRAINT SWEEP
# =====================================================================
if df1_base is not None and df1_mkt is not None:
    
    # --- Fig 1a: Composition of Placements (Absolute, Scientific Notation) ---
    fig1a, ax1a = plt.subplots(figsize=FIG_SIZE)
    
    ax1a.plot(df1_base['sweep_value'], df1_base['true_optimal_deliveries'], color=COLOR_OPTIMAL, marker='o', linestyle='--', linewidth=2, label=f'Optimal ({LABEL_BASELINE})')
    add_ci(ax1a, df1, 'BASELINE', 'sweep_value', 'true_optimal_deliveries', COLOR_OPTIMAL)
    
    ax1a.plot(df1_base['sweep_value'], df1_base['suboptimal_deliveries'], color=COLOR_SUBOPTIMAL, marker='s', linestyle='--', linewidth=2, label=f'Suboptimal ({LABEL_BASELINE})')
    add_ci(ax1a, df1, 'BASELINE', 'sweep_value', 'suboptimal_deliveries', COLOR_SUBOPTIMAL)
    
    ax1a.plot(df1_base['sweep_value'], df1_base['sla_violations'], color=COLOR_SLA, marker='^', linestyle='--', linewidth=2, label=f'SLA Violations ({LABEL_BASELINE})')
    add_ci(ax1a, df1, 'BASELINE', 'sweep_value', 'sla_violations', COLOR_SLA)
    
    ax1a.plot(df1_mkt['sweep_value'], df1_mkt['true_optimal_deliveries'], color=COLOR_OPTIMAL, marker='D', linestyle='-', linewidth=3, markersize=7, label=f'Optimal ({LABEL_MARKETPLACE})')
    add_ci(ax1a, df1, 'WEIGHTED_UTILITY', 'sweep_value', 'true_optimal_deliveries', COLOR_OPTIMAL)
    
    ax1a.plot(df1_mkt['sweep_value'], df1_mkt['suboptimal_deliveries'], color=COLOR_SUBOPTIMAL, marker='X', linestyle='-', linewidth=3, markersize=8, label=f'Suboptimal ({LABEL_MARKETPLACE})')
    add_ci(ax1a, df1, 'WEIGHTED_UTILITY', 'sweep_value', 'suboptimal_deliveries', COLOR_SUBOPTIMAL)
    
    ax1a.plot(df1_mkt['sweep_value'], df1_mkt['sla_violations'], color=COLOR_SLA, marker='v', linestyle='-', linewidth=3, markersize=8, label=f'SLA Violations ({LABEL_MARKETPLACE})')
    add_ci(ax1a, df1, 'WEIGHTED_UTILITY', 'sweep_value', 'sla_violations', COLOR_SLA)
    
    ax1a.set_xlabel('Proportion of Budget-Constrained Requests', fontweight='bold')
    ax1a.set_ylabel('Number of Requests', fontweight='bold')
    ax1a.ticklabel_format(style='sci', axis='y', scilimits=(0,0))
    ax1a.legend(loc='best', fontsize='small', ncol=2)
    plt.tight_layout()
    plt.savefig('fig1a_budget_composition_absolute.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 1b: Composition of Placements (% of Total Placements) ---
    fig1b, ax1b = plt.subplots(figsize=FIG_SIZE)
    
    ax1b.plot(df1_base['sweep_value'], df1_base['optimal_pct'], color=COLOR_OPTIMAL, marker='o', linestyle='--', linewidth=2, label=f'Optimal ({LABEL_BASELINE})')
    add_ci(ax1b, df1, 'BASELINE', 'sweep_value', 'optimal_pct', COLOR_OPTIMAL)
    
    ax1b.plot(df1_base['sweep_value'], df1_base['suboptimal_pct'], color=COLOR_SUBOPTIMAL, marker='s', linestyle='--', linewidth=2, label=f'Suboptimal ({LABEL_BASELINE})')
    add_ci(ax1b, df1, 'BASELINE', 'sweep_value', 'suboptimal_pct', COLOR_SUBOPTIMAL)
    
    ax1b.plot(df1_base['sweep_value'], df1_base['sla_pct'], color=COLOR_SLA, marker='^', linestyle='--', linewidth=2, label=f'SLA Violations ({LABEL_BASELINE})')
    add_ci(ax1b, df1, 'BASELINE', 'sweep_value', 'sla_pct', COLOR_SLA)
    
    ax1b.plot(df1_mkt['sweep_value'], df1_mkt['optimal_pct'], color=COLOR_OPTIMAL, marker='D', linestyle='-', linewidth=3, markersize=7, label=f'Optimal ({LABEL_MARKETPLACE})')
    add_ci(ax1b, df1, 'WEIGHTED_UTILITY', 'sweep_value', 'optimal_pct', COLOR_OPTIMAL)
    
    ax1b.set_xlabel('Proportion of Budget-Constrained Requests', fontweight='bold')
    ax1b.set_ylabel('Percentage of Total Placements (%)', fontweight='bold')
    ax1b.set_ylim(-2, 105) 
    ax1b.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
    ax1b.legend(loc='best', fontsize='small', ncol=1) 
    plt.tight_layout()
    plt.savefig('fig1b_budget_composition_pct.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 2: The Orchestration Penalty (Unified System Degradation plotted as Optimality Gap) ---
    fig2, ax2 = plt.subplots(figsize=FIG_SIZE)
    
    col_1 = 'unified_system_degradation' if 'unified_system_degradation' in df1_base.columns else 'avg_optimality_gap'
    
    ax2.plot(df1_base['sweep_value'], df1_base[col_1], color=color_baseline, marker='o', linestyle='-', linewidth=2.5, label=LABEL_BASELINE)
    add_ci(ax2, df1, 'BASELINE', 'sweep_value', col_1, color_baseline)
    
    ax2.plot(df1_mkt['sweep_value'], df1_mkt[col_1], color=color_marketplace, marker='s', linestyle='-', linewidth=2.5, label=LABEL_MARKETPLACE)
    add_ci(ax2, df1, 'WEIGHTED_UTILITY', 'sweep_value', col_1, color_marketplace)
    
    ax2.set_xlabel('Proportion of Budget-Constrained Requests', fontweight='bold')
    ax2.set_ylabel('Average Optimality Gap (%)', fontweight='bold')
    ax2.set_ylim(shared_deg_ylim)
    ax2.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0, decimals=0))
    ax2.legend(loc='upper left')
    plt.tight_layout()
    plt.savefig('fig2_budget_optimality_gap.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 3: Placement Accuracy (Budget) ---
    fig3, ax3 = plt.subplots(figsize=FIG_SIZE)
    ax3.plot(df1_mkt['sweep_value'], df1_mkt['ground_truth_matches'], color='black', linestyle=':', linewidth=3, label='Theoretical Ground Truth')
    add_ci(ax3, df1, 'WEIGHTED_UTILITY', 'sweep_value', 'ground_truth_matches', 'black')
    
    ax3.plot(df1_base['sweep_value'], df1_base['deliveries'], color=color_baseline, marker='o', linestyle='-', linewidth=2.5, alpha=0.8, label=f'Placements ({LABEL_BASELINE})')
    add_ci(ax3, df1, 'BASELINE', 'sweep_value', 'deliveries', color_baseline)
    
    ax3.plot(df1_mkt['sweep_value'], df1_mkt['deliveries'], color=color_marketplace, marker='s', linestyle='--', linewidth=2.5, label=f'Placements ({LABEL_MARKETPLACE})')
    add_ci(ax3, df1, 'WEIGHTED_UTILITY', 'sweep_value', 'deliveries', color_marketplace)
    
    ax3.set_xlabel('Proportion of Budget-Constrained Requests', fontweight='bold')
    ax3.set_ylabel('Total Placements', fontweight='bold')
    ax3.set_ylim(df1_mkt['deliveries'].min() * 0.90, df1_base['deliveries'].max() * 1.05)
    ax3.legend(loc='lower left')
    plt.tight_layout()
    plt.savefig('fig3_budget_delivery_accuracy.pdf', format='pdf', bbox_inches='tight')


# =====================================================================
# PART B: EXPERIMENTS 2 & 3 - TOPOLOGICAL ADAPTABILITY
# =====================================================================
if df2_mkt is not None and df3_mkt is not None and df3_base is not None:
    
    # --- Fig 4: Average Placement Cost Comparison ---
    fig4, ax4 = plt.subplots(figsize=FIG_SIZE)
    ax4.plot(df3_mkt['sweep_value'], df3_mkt['avg_delivered_utility'], color='#2ca02c', marker='s', linestyle='-', linewidth=2.5, markersize=8, label='Edge-Cloud')
    add_ci(ax4, df3, 'WEIGHTED_UTILITY', 'sweep_value', 'avg_delivered_utility', '#2ca02c')
    
    ax4.plot(df2_mkt['sweep_value'], df2_mkt['avg_delivered_utility'], color='#1f77b4', marker='o', linestyle='--', linewidth=2.5, markersize=8, label='Cloud')
    add_ci(ax4, df2, 'WEIGHTED_UTILITY', 'sweep_value', 'avg_delivered_utility', '#1f77b4')
    
    ax4.set_xlabel('Proportion of Strict Latency Requests', fontweight='bold')
    ax4.set_ylabel('Average Placement Cost', fontweight='bold')
    ax4.set_ylim(0, max(df2_mkt['avg_delivered_utility'].max(), df3_mkt['avg_delivered_utility'].max()) * 1.1)
    ax4.legend(loc='lower right', frameon=True)
    plt.tight_layout()
    plt.savefig('fig4_utility_cost_comparison.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 5: Proactive Drops Percentage Comparison ---
    fig5, ax5 = plt.subplots(figsize=FIG_SIZE)
    ax5.plot(df3_mkt['sweep_value'], df3_mkt['shielded_pct'], color='#ff7f0e', marker='P', linestyle='-', linewidth=2.5, markersize=8, label='Edge-Cloud')
    add_ci(ax5, df3, 'WEIGHTED_UTILITY', 'sweep_value', 'shielded_pct', '#ff7f0e')
    
    ax5.plot(df2_mkt['sweep_value'], df2_mkt['shielded_pct'], color='#d62728', marker='X', linestyle='--', linewidth=2.5, markersize=8, label='Cloud')
    add_ci(ax5, df2, 'WEIGHTED_UTILITY', 'sweep_value', 'shielded_pct', '#d62728')
    
    ax5.set_xlabel('Proportion of Strict Latency Requests', fontweight='bold')
    ax5.set_ylabel('Percentage of Proactive Drops (%)', fontweight='bold')
    ax5.set_ylim(-2, max(df2_mkt['shielded_pct'].max(), df3_mkt['shielded_pct'].max()) + 5)
    ax5.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
    ax5.legend(loc='upper left', frameon=True)
    plt.tight_layout()
    plt.savefig('fig5_shielded_percentage_comparison.pdf', format='pdf', bbox_inches='tight')

    # --- Fig Exp3_Comp: Placement Composition in Edge-Cloud ---
    fig_e3_comp, ax_e3_comp = plt.subplots(figsize=FIG_SIZE)
    
    ax_e3_comp.plot(df3_base['sweep_value'], df3_base['optimal_pct'], color=COLOR_OPTIMAL, marker='o', linestyle='--', linewidth=2, label=f'Optimal ({LABEL_BASELINE})')
    add_ci(ax_e3_comp, df3, 'BASELINE', 'sweep_value', 'optimal_pct', COLOR_OPTIMAL)
    
    ax_e3_comp.plot(df3_base['sweep_value'], df3_base['suboptimal_pct'], color=COLOR_SUBOPTIMAL, marker='s', linestyle='--', linewidth=2, label=f'Suboptimal ({LABEL_BASELINE})')
    add_ci(ax_e3_comp, df3, 'BASELINE', 'sweep_value', 'suboptimal_pct', COLOR_SUBOPTIMAL)
    
    ax_e3_comp.plot(df3_base['sweep_value'], df3_base['sla_pct'], color=COLOR_SLA, marker='^', linestyle='--', linewidth=2, label=f'SLA Violations ({LABEL_BASELINE})')
    add_ci(ax_e3_comp, df3, 'BASELINE', 'sweep_value', 'sla_pct', COLOR_SLA)
    
    ax_e3_comp.plot(df3_mkt['sweep_value'], df3_mkt['optimal_pct'], color=COLOR_OPTIMAL, marker='D', linestyle='-', linewidth=3, markersize=7, label=f'Optimal ({LABEL_MARKETPLACE})')
    add_ci(ax_e3_comp, df3, 'WEIGHTED_UTILITY', 'sweep_value', 'optimal_pct', COLOR_OPTIMAL)
    
    ax_e3_comp.set_xlabel('Proportion of Strict Latency Requests', fontweight='bold')
    ax_e3_comp.set_ylabel('Percentage of Total Placements (%)', fontweight='bold')
    ax_e3_comp.set_ylim(-2, 105) 
    ax_e3_comp.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
    ax_e3_comp.legend(loc='center left', fontsize='small', ncol=1) 
    plt.tight_layout()
    plt.savefig('fig_exp3_composition_pct.pdf', format='pdf', bbox_inches='tight')

    # --- Fig Exp3_Gap: Average Optimality Gap (Using Unified System Degradation) ---
    fig_e3_gap, ax_e3_gap = plt.subplots(figsize=FIG_SIZE)
    col_3 = 'unified_system_degradation' if 'unified_system_degradation' in df3_base.columns else 'avg_optimality_gap'
    
    ax_e3_gap.plot(df3_base['sweep_value'], df3_base[col_3], color=color_baseline, marker='o', linestyle='-', linewidth=2.5, label=LABEL_BASELINE)
    add_ci(ax_e3_gap, df3, 'BASELINE', 'sweep_value', col_3, color_baseline)
    
    ax_e3_gap.plot(df3_mkt['sweep_value'], df3_mkt[col_3], color=color_marketplace, marker='s', linestyle='-', linewidth=2.5, label=LABEL_MARKETPLACE)
    add_ci(ax_e3_gap, df3, 'WEIGHTED_UTILITY', 'sweep_value', col_3, color_marketplace)
    
    ax_e3_gap.set_xlabel('Proportion of Strict Latency Requests', fontweight='bold')
    ax_e3_gap.set_ylabel('Average Optimality Gap (%)', fontweight='bold')
    ax_e3_gap.set_ylim(shared_deg_ylim)
    ax_e3_gap.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0, decimals=0))
    ax_e3_gap.legend(loc='upper left')
    plt.tight_layout()
    plt.savefig('fig_exp3_optimality_gap.pdf', format='pdf', bbox_inches='tight')


# =====================================================================
# PART C: EXPERIMENT 4 - AGGREGATION THRESHOLD SWEEP (30% Edge Load)
# =====================================================================
if df4 is not None:
    df4_mean = df4.groupby('sweep_value').mean(numeric_only=True).reset_index()
    shared_ylim = (-2, 105)

    # --- Fig 6: State Compression vs Computational Overhead ---
    fig6, ax6 = plt.subplots(figsize=FIG_SIZE)
    ax6_twin = ax6.twinx()
    ax6_twin.grid(False) 
    
    l1 = ax6.plot(df4_mean['sweep_value'], df4_mean['table_size_avg'], color=colors[0], marker='o', linewidth=2.5, label='Avg OfferIndex Size')
    add_ci(ax6, df4, None, 'sweep_value', 'table_size_avg', colors[0])
    
    l2 = ax6_twin.plot(df4_mean['sweep_value'], df4_mean['qos_evaluations'], color=colors[1], marker='s', linestyle='--', linewidth=2.5, label='Total Constraint Evaluations')
    add_ci(ax6_twin, df4, None, 'sweep_value', 'qos_evaluations', colors[1])
    
    ax6.set_xlabel('Aggregation Threshold', fontweight='bold')
    ax6.set_ylabel('Average OfferIndex Size', color=colors[0], fontweight='bold')
    ax6_twin.set_ylabel('Total Constraint Evaluations', color=colors[1], fontweight='bold')
    ax6.tick_params(axis='y', labelcolor=colors[0])
    ax6_twin.tick_params(axis='y', labelcolor=colors[1])
    
    lines_6 = l1 + l2
    ax6.legend(lines_6, [l.get_label() for l in lines_6], loc='upper right')
    plt.tight_layout()
    plt.savefig('fig6_compression_overhead.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 7: Orchestration Failures under Aggregation (Linear, % of Total Requests) ---
    fig7, ax7 = plt.subplots(figsize=FIG_SIZE)
    ax7.plot(df4_mean['sweep_value'], df4_mean['dead_ends_pct'], marker='o', linestyle='-', linewidth=2.5, color=colors[0], label='False Positive Dispatches')
    add_ci(ax7, df4, None, 'sweep_value', 'dead_ends_pct', colors[0])
    
    ax7.plot(df4_mean['sweep_value'], df4_mean['shielded_pct'], marker='^', linestyle='--', linewidth=2, color=colors[1], alpha=0.7, label='Proactive Drops')
    add_ci(ax7, df4, None, 'sweep_value', 'shielded_pct', colors[1])
    
    ax7.set_xlabel('Aggregation Threshold', fontweight='bold')
    ax7.set_ylabel('Percentage of Total Requests (%)', fontweight='bold')
    ax7.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
    ax7.set_ylim(shared_ylim)
    ax7.legend(loc='best')
    plt.tight_layout()
    plt.savefig('fig7_orchestration_failures.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 7b: Orchestration Failures Breakdown (Linear, % of Total Requests) ---
    fig7b, ax7b = plt.subplots(figsize=FIG_SIZE)
    
    ax7b.plot(df4_mean['sweep_value'], df4_mean['false_positive_pct'], marker='o', linestyle='-', linewidth=2.5, color=colors[0], label='False Positive Dispatches')
    add_ci(ax7b, df4, None, 'sweep_value', 'false_positive_pct', colors[0])
    
    ax7b.plot(df4_mean['sweep_value'], df4_mean['undelivered_pct'], marker='s', linestyle='-', linewidth=2.5, color=colors[3], label='Undelivered')
    add_ci(ax7b, df4, None, 'sweep_value', 'undelivered_pct', colors[3])
    
    ax7b.plot(df4_mean['sweep_value'], df4_mean['shielded_pct'], marker='^', linestyle='--', linewidth=2, color=colors[1], alpha=0.7, label='Proactive Drops')
    add_ci(ax7b, df4, None, 'sweep_value', 'shielded_pct', colors[1])
    
    ax7b.set_xlabel('Aggregation Threshold', fontweight='bold')
    ax7b.set_ylabel('Percentage of Total Requests (%)', fontweight='bold')
    ax7b.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
    ax7b.set_ylim(shared_ylim)
    ax7b.legend(loc='best')
    plt.tight_layout()
    plt.savefig('fig7b_orchestration_failures_breakdown.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 7c: Orchestration Failures Breakdown (Zoomed / Auto-scaled Y-axis) ---
    fig7c, ax7c = plt.subplots(figsize=FIG_SIZE)
    
    ax7c.plot(df4_mean['sweep_value'], df4_mean['false_positive_pct'], marker='o', linestyle='-', linewidth=2.5, color=colors[0], label='False Positive Dispatches')
    add_ci(ax7c, df4, None, 'sweep_value', 'false_positive_pct', colors[0])
    
    ax7c.plot(df4_mean['sweep_value'], df4_mean['undelivered_pct'], marker='s', linestyle='-', linewidth=2.5, color=colors[3], label='Undelivered')
    add_ci(ax7c, df4, None, 'sweep_value', 'undelivered_pct', colors[3])
    
    ax7c.plot(df4_mean['sweep_value'], df4_mean['shielded_pct'], marker='^', linestyle='--', linewidth=2, color=colors[1], alpha=0.7, label='Proactive Drops')
    add_ci(ax7c, df4, None, 'sweep_value', 'shielded_pct', colors[1])
    
    ax7c.set_xlabel('Aggregation Threshold', fontweight='bold')
    ax7c.set_ylabel('Percentage of Total Requests (%)', fontweight='bold')
    
    # We remove the 100% cap (shared_ylim) to let the graph automatically zoom in on the actual data peaks.
    # We also remove `decimals=0` from the formatter so that if it zooms in to fractions of a percent, the labels still make sense.
    ax7c.yaxis.set_major_formatter(mtick.PercentFormatter())
    ax7c.set_ylim(bottom=-0.5) # Keeps the bottom anchored just below zero for a clean visual.
    
    ax7c.legend(loc='best')
    plt.tight_layout()
    plt.savefig('fig7c_orchestration_failures_zoomed.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 8: Relative Utility Degradation (Optimality Gap in %) ---
    fig8, ax8 = plt.subplots(figsize=FIG_SIZE)
    col_4 = 'unified_system_degradation' if 'unified_system_degradation' in df4_mean.columns else 'avg_optimality_gap'
    
    ax8.plot(df4_mean['sweep_value'], df4_mean[col_4], marker='o', linewidth=2.5, color=colors[0], label='Avg Optimality Gap')
    add_ci(ax8, df4, None, 'sweep_value', col_4, colors[0])
        
    ax8.set_xlabel('Aggregation Threshold', fontweight='bold')
    ax8.set_ylabel('Average Optimality Gap', fontweight='bold')
    ax8.yaxis.set_major_formatter(mtick.PercentFormatter(xmax=1.0, decimals=0))
    ax8.set_ylim(bottom=-0.02)
    ax8.legend(loc='best')
    plt.tight_layout()
    plt.savefig('fig8_optimality_gap_pct.pdf', format='pdf', bbox_inches='tight')

    # --- Fig 9: Placement Accuracy (% of Total Requests) ---
    fig9, ax9 = plt.subplots(figsize=FIG_SIZE)
    ax9.plot(df4_mean['sweep_value'], df4_mean['optimal_pct'], marker='D', linestyle='-', linewidth=2.5, color=COLOR_OPTIMAL, label='Optimal Placements')
    add_ci(ax9, df4, None, 'sweep_value', 'optimal_pct', COLOR_OPTIMAL)
    
    ax9.plot(df4_mean['sweep_value'], df4_mean['suboptimal_pct'], marker='X', linestyle='--', linewidth=2.5, color=COLOR_SUBOPTIMAL, label='Suboptimal Placements')
    add_ci(ax9, df4, None, 'sweep_value', 'suboptimal_pct', COLOR_SUBOPTIMAL)
    
    ax9.set_xlabel('Aggregation Threshold', fontweight='bold')
    ax9.set_ylabel('Percentage of Total Requests (%)', fontweight='bold')
    ax9.yaxis.set_major_formatter(mtick.PercentFormatter(decimals=0))
    ax9.set_ylim(shared_ylim)
    ax9.legend(loc='best')
    plt.tight_layout()
    plt.savefig('fig9_delivery_accuracy.pdf', format='pdf', bbox_inches='tight')

print("\nAll figures generated sequentially. Fig 7c generated with dynamically scaled Y-axis.")