import pandas as pd
import numpy as np
import os
import argparse

def process_azure_traces(data_dir, output_file, top_n=1000, day="d01"):
    """
    Parses the Azure 2019 Serverless trace, aggregates metrics, and maps 
    alphanumeric hashes to sequential longs.
    """
    print(f"--- FaaS Marketplace: Azure Trace Pre-processor ---")
    print(f"Target Day: {day} | Extracting Top {top_n} Functions")

    # File paths
    invocations_file = os.path.join(data_dir, f"invocations_per_function_md.anon.{day}.csv")
    durations_file = os.path.join(data_dir, f"function_durations_percentiles.anon.{day}.csv")
    memory_file = os.path.join(data_dir, f"app_memory_percentiles.anon.{day}.csv")

    # 1. Process Invocations (Heavy Lifting)
    print("1. Aggregating Invocations...")
    # The first 4 columns are HashOwner, HashApp, HashFunction, Trigger. 
    # The rest are minute bins (1 to 1440)
    invocations_df = pd.read_csv(invocations_file)
    
    # SHIFT INDEX TO 4 to skip the 'Trigger' string column
    minute_columns = invocations_df.columns[4:] 
    
    # Enforce numeric_only=True to guarantee mathematically safe tensor operations
    invocations_df['InvocationCount'] = invocations_df[minute_columns].sum(axis=1, numeric_only=True)
    
    # Keep only what we need to save memory
    invocations_df = invocations_df[['HashOwner', 'HashApp', 'HashFunction', 'InvocationCount']]

    # 2. Process Durations
    print("2. Extracting Execution Durations...")
    durations_df = pd.read_csv(durations_file)
    # We need the 'Average' duration column
    durations_df = durations_df[['HashOwner', 'HashApp', 'HashFunction', 'Average']]
    durations_df.rename(columns={'Average': 'AvgDurationMs'}, inplace=True)

    # 3. Process Memory (Note: Memory is recorded per App, not per Function)
    print("3. Extracting Memory Footprints...")
    memory_df = pd.read_csv(memory_file)
    memory_df = memory_df[['HashOwner', 'HashApp', 'AverageAllocatedMb']]
    memory_df.rename(columns={'AverageAllocatedMb': 'AvgMemoryMB'}, inplace=True)

    # 4. Merge Datasets
    print("4. Merging and Aligning Data...")
    # Merge Durations into Invocations
    merged_df = pd.merge(invocations_df, durations_df, on=['HashOwner', 'HashApp', 'HashFunction'], how='inner')
    
    # Merge Memory into the result (Broadcasting App memory to its constituent Functions)
    merged_df = pd.merge(merged_df, memory_df, on=['HashOwner', 'HashApp'], how='inner')

    # Clean up any potential NaNs generated by missing trace data
    merged_df.dropna(inplace=True)

    # 5. Extract the "Marketplace Top N" (Zipfian Skew)
    print(f"5. Sorting and extracting the Top {top_n} most popular functions...")
    merged_df.sort_values(by='InvocationCount', ascending=False, inplace=True)
    top_functions_df = merged_df.head(top_n).copy()

    # 6. Map to Paillier-Compatible Long IDs
    # Our HE substrate cannot encrypt Azure's SHA-256 string hashes. We map them to 1L -> NL.
    print("6. Generating Paillier-compatible Integer IDs...")
    top_functions_df['FunctionID'] = range(1, len(top_functions_df) + 1)

    # 7. Final Formatting and Export
    final_df = top_functions_df[['FunctionID', 'InvocationCount', 'AvgDurationMs', 'AvgMemoryMB']]
    
    # Ensure types are correct for the Java parser
    final_df = final_df.astype({
        'FunctionID': 'int64', 
        'InvocationCount': 'int64',
        'AvgDurationMs': 'float64',
        'AvgMemoryMB': 'float64'
    })

    final_df.to_csv(output_file, index=False)
    print(f"\n[SUCCESS] Pre-processed trace saved to: {output_file}")
    print(f"Schema: {list(final_df.columns)}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pre-process Azure 2019 Serverless Traces for FaaS Marketplace Simulator")
    parser.add_argument("--data-dir", type=str, required=True, help="Directory containing the raw Azure CSV files")
    parser.add_argument("--output", type=str, default="../resources/azure_marketplace_top1000.csv", help="Path for the output CSV")
    parser.add_argument("--top", type=int, default=1000, help="Number of top functions to extract")
    parser.add_argument("--day", type=str, default="d01", help="Which day to parse (e.g., d01, d02)")
    
    args = parser.parse_args()
    process_azure_traces(args.data_dir, args.output, args.top, args.day)