package marketplace.common;

import java.util.Map;

/**
 * Defines the standard schema for QoS metrics in the FaaS Marketplace.
 * Centralizes the definition of metric names, order, and optimization direction.
 */
public class MarketplaceMetricSchema {

    /**
     * UTILITY WEIGHT ALIGNMENTS:
     * In FaaS, multi-objective optimization requires standardizing units.
     * Latency is measured in absolute Milliseconds (ms).
     * Cost is measured in USD per 1,000,000 executions (assuming a 1GB memory profile).
     * Reliability is measured as a percentage (e.g., 0.999 for 3-nines).
     * Bandwidth is measured in Megabits per second (Mbps).
     */
    
    // Metric Names (Explicitly defining the FaaS mathematical units)
    public static final String METRIC_LATENCY = "latency_ms";
    public static final String METRIC_COST = "cost_per_1m_invocations_usd";
    public static final String METRIC_RELIABILITY = "reliability_nines";
    public static final String METRIC_BANDWIDTH = "bandwidth_mbps";

    // =========================================================================
    // SYSTEM MAXIMUMS (Operational SLA Limits for Hybrid Normalization)
    // =========================================================================
    
    // LATENCY (Minimize): 1000.0 milliseconds
    // Justification: Bounds the worst-case scenario (Cloud Client 600ms SLA + 
    // Edge Cold-Start Penalty 200ms + Cross-country Network Delay ~150ms).
    public static final double SYSTEM_MAX_LATENCY = 1000.0;

    // COST (Minimize): 150.0 (USD / 1M Invocations)
    // Justification: Bounds the highest theoretical premium Edge budget ($110.00) 
    // requested by latency-critical FaaS telemetry clients.
    public static final double SYSTEM_MAX_COST = 150.0;

    // RELIABILITY (Maximize): 1.0 (Probability / Nines of Availability)
    // Justification: A perfect mathematical probability bound.
    public static final double SYSTEM_MAX_RELIABILITY = 1.0;

    // BANDWIDTH (Maximize): 1000.0 (Megabits per second - Mbps)
    // Justification: Bounds the highest maximum throughput generated by the 
    // Cloud Datacenter fiber-optic profiles (800 - 1000 Mbps).
    public static final double SYSTEM_MAX_BANDWIDTH = 1000.0;

    // 1. The Fixed Order of Dimensions in the Hypercube/Vector
    public static final String[] KEYS = {
        METRIC_LATENCY,      // Index 0
        METRIC_COST,         // Index 1
        METRIC_RELIABILITY,  // Index 2
        METRIC_BANDWIDTH,    // Index 3
    };

    // 2. Optimization Direction: True = Minimize, False = Maximize
    public static final Map<String, Boolean> DIRECTIONS = Map.of(
        METRIC_LATENCY,      true,  // Minimize (Lower latency is better)
        METRIC_COST,         true,  // Minimize (Lower cost is better)
        METRIC_RELIABILITY,  false, // Maximize (Higher reliability is better)
        METRIC_BANDWIDTH,    false  // Maximize (Higher throughput is better)
    );

    // Short labels for compact simulation logging
    public static final Map<String, String> SHORT_NAMES = Map.of(
        METRIC_LATENCY, "Lat",
        METRIC_COST, "Cst",
        METRIC_RELIABILITY, "Rel",
        METRIC_BANDWIDTH, "Bw"
    );

    // Quick Lookup Indices
    public static final int IDX_LATENCY = 0;
    
    // 1.665 ms of network delay per 1 degree of geographical distance 
    // (Roughly 111km per degree over standard fiber)
    public static final double DISTANCE_TO_TIME_FACTOR = 1.665;

    /**
     * @return The index of a specific metric key, or -1 if not found.
     */
    public static int getIndexOf(String key) {
        for (int i = 0; i < KEYS.length; i++) {
            if (KEYS[i].equals(key)) return i;
        }
        return -1;
    }

    /**
     * Retrieves the predefined system maximum bound for a given metric.
     * This ensures the homomorphic HyperCubes map values flawlessly between 0.0 and 1.0.
     */
    public static double getSystemMax(String key) {
        if (METRIC_LATENCY.equals(key)) return SYSTEM_MAX_LATENCY;
        if (METRIC_COST.equals(key)) return SYSTEM_MAX_COST;
        if (METRIC_RELIABILITY.equals(key)) return SYSTEM_MAX_RELIABILITY;
        if (METRIC_BANDWIDTH.equals(key)) return SYSTEM_MAX_BANDWIDTH;
        return Double.MAX_VALUE;
    }
}